[package]
name = "hpc_parafac"
version = "0.1.0"
edition = "2021"

[dependencies]

ndarray = "0.16" 
rand = "*"

faer = "*"
faer-ext= "*"

#mpi = "0.8.0"

rayon = "1.5"  # Verifique a vers√£o mais recente







